FROM node:22.14.0-alpine

# Install pnpm globally
RUN corepack enable && corepack prepare pnpm@10.32.1 --activate

WORKDIR /app

COPY package.json pnpm-workspace.yaml pnpm-lock.yaml ./

COPY packages/contracts/package.json packages/contracts/package.json

COPY apps/admin/package.json apps/admin/package.json

RUN pnpm install

COPY packages/contracts ./packages/contracts
COPY apps/admin ./apps/admin 
