export type CategoriesName = 'TERES SIGNATURE COCKTAILS' | 'COCKTAILS' | 'CLASSIC COCKTAILS';

export type CocktailItem = {
  alt: string;
  title: string;
  description: string;
  price: string;
  allergies: string;
  allergies_long: string;
  allergiesList: string[];
  category: CategoriesName;
  src: string;
};

export type FoodCategory = {
  id: CategoriesName;
  name: string;
  sortOrder: number;
};

export const cocktailCategories: Record<CategoriesName, FoodCategory> = {
  'TERES SIGNATURE COCKTAILS': {
    id: 'TERES SIGNATURE COCKTAILS',
    name: 'TERES SIGNATURE COCKTAILS',
    sortOrder: 1,
  },
  COCKTAILS: {
    id: 'COCKTAILS',
    name: 'COCKTAILS',
    sortOrder: 2,
  },
  'CLASSIC COCKTAILS': {
    id: 'CLASSIC COCKTAILS',
    name: 'CLASSIC COCKTAILS',
    sortOrder: 3,
  },
};

export const cocktailData: CocktailItem[] = [
  // -------------------------- TERES SIGNATURE COCKTAILS --------------------------
  {
    alt: 'Whiscorn cocktail',
    title: 'Whiscorn',
    description:
      'Bourbon Whiskey, Saffron Syrup, Pineapple Juice, Orange Juice, Fresh Lemon Juice, Egg White, Orange Bitters',
    price: '5.500',
    allergies: '',
    allergies_long: '',
    allergiesList: [],
    category: 'TERES SIGNATURE COCKTAILS',
    src: '/cocktails/Whiscorn.png',
  },
  {
    alt: 'Of The Moment cocktail',
    title: 'Of The Moment',
    description:
      'White Rum, Elder Flower Liqueur, Midori, Apple Juice, Fresh Lemon Juice, Ginger Syrup, Aromatic Bitters',
    price: '5.500',
    allergies: '',
    allergies_long: '',
    allergiesList: [],
    category: 'TERES SIGNATURE COCKTAILS',
    src: '/cocktails/Of The Moment.png',
  },
  {
    alt: 'Midnight Reverie Bourbon cocktail',
    title: 'Midnight Reverie Bourbon',
    description: 'Whiskey, Coffee Liqueur, Crème de Cacao White Liqueur',
    price: '5.500',
    allergies: '',
    allergies_long: '',
    allergiesList: [],
    category: 'TERES SIGNATURE COCKTAILS',
    src: '/cocktails/Midnight Reverie Bourbon.png',
  },
  {
    alt: 'Azul Fuego cocktail',
    title: 'Azul Fuego',
    description: 'Tequila Silver, Blueberry Syrup, Ginger Syrup, Cointreau, Fresh Lime Juice',
    price: '5.500',
    allergies: '',
    allergies_long: '',
    allergiesList: [],
    category: 'TERES SIGNATURE COCKTAILS',
    src: '/cocktails/Azul Fuego.png',
  },
  {
    alt: 'Dream Forest cocktail',
    title: 'Dream Forest',
    description: 'Gin, Frangelico, Fresh Lemon Juice, Simple Syrup, Aromatic Bitters, Egg White',
    price: '5.500',
    allergies: '',
    allergies_long: '',
    allergiesList: [],
    category: 'TERES SIGNATURE COCKTAILS',
    src: '/cocktails/Dream Forest.png',
  },
  {
    alt: 'Port Light cocktail',
    title: 'Port Light',
    description: 'Jameson, K.W.V Brandy, Fresh Lemon Juice, Grenadine, Passionfruit Puree',
    price: '5.500',
    allergies: '',
    allergies_long: '',
    allergiesList: [],
    category: 'TERES SIGNATURE COCKTAILS',
    src: '/cocktails/Port Light.png',
  },
  {
    alt: 'Rossette cocktail',
    title: 'Rossette',
    description: 'Pink Gin, Cointreau, Grapefruit Juice, Rose Syrup, Fresh Lemon Juice, Egg White',
    price: '5.500',
    allergies: '',
    allergies_long: '',
    allergiesList: [],
    category: 'TERES SIGNATURE COCKTAILS',
    src: '/cocktails/rosette.png',
  },
  {
    alt: 'Berry Smash cocktail',
    title: 'Berry Smash',
    description: 'Vodka, mixed berry purée, fresh lemon juice, simple syrup, mint leaves, crushed ice',
    price: '5.500',
    allergies: '',
    allergies_long: '',
    allergiesList: [],
    category: 'TERES SIGNATURE COCKTAILS',
    src: '/cocktails/berry smash.png',
  },
  {
    alt: 'The Ultimate cocktail',
    title: 'The Ultimate',
    description: 'Vodka, gin, white rum, tequila silver, triple sec, fresh lemon juice, simple syrup, splash of soda',
    price: '5.500',
    allergies: '',
    allergies_long: '',
    allergiesList: [],
    category: 'TERES SIGNATURE COCKTAILS',
    src: '/cocktails/the ultimate.png',
  },
  {
    alt: 'Dark Phoenix cocktail',
    title: 'Dark Phoenix',
    description: 'Dark rum, bourbon whiskey, coffee liqueur, fresh lime juice, cinnamon syrup, aromatic bitters',
    price: '5.500',
    allergies: '',
    allergies_long: '',
    allergiesList: [],
    category: 'TERES SIGNATURE COCKTAILS',
    src: '/cocktails/Dark Phoenix.png',
  },
  {
    alt: 'Green Feather cocktail',
    title: 'Green Feather',
    description: 'Gin, Midori, elderflower liqueur, fresh lime juice, simple syrup, egg white',
    price: '5.500',
    allergies: '',
    allergies_long: '',
    allergiesList: [],
    category: 'TERES SIGNATURE COCKTAILS',
    src: '/cocktails/green feather.png',
  },
  {
    alt: "Dou Dou's Daddy cocktail",
    title: "Dou Dou's Daddy",
    description: 'Spiced rum, passionfruit purée, pineapple juice, fresh lime juice, vanilla syrup, aromatic bitters',
    price: '5.500',
    allergies: '',
    allergies_long: '',
    allergiesList: [],
    category: 'TERES SIGNATURE COCKTAILS',
    src: '/cocktails/Dou Dou’s Daddy.png',
  },
  {
    alt: 'Ullord cocktail',
    title: 'Ullord',
    description: 'Whiskey, apple juice, ginger syrup, fresh lemon juice, honey syrup, aromatic bitters',
    price: '5.500',
    allergies: '',
    allergies_long: '',
    allergiesList: [],
    category: 'TERES SIGNATURE COCKTAILS',
    src: '/cocktails/ullord.png',
  },
  {
    alt: 'Sonic cocktail',
    title: 'Sonic',
    description: 'Gin, blue curaçao, fresh lemon juice, simple syrup, tonic water',
    price: '5.500',
    allergies: '',
    allergies_long: '',
    allergiesList: [],
    category: 'TERES SIGNATURE COCKTAILS',
    src: '/cocktails/sonic.png',
  },
  {
    alt: 'Green Fiddle cocktail',
    title: 'Green Fiddle',
    description: 'Gin, cucumber juice, fresh lime juice, basil syrup, elderflower liqueur, soda water',
    price: '5.500',
    allergies: '',
    allergies_long: '',
    allergiesList: [],
    category: 'TERES SIGNATURE COCKTAILS',
    src: '/cocktails/Green Fiddle.png',
  },
  {
    alt: 'Whiskey Wick cocktail',
    title: 'Whiskey Wick',
    description: 'Bourbon whiskey, orange bitters, honey syrup, fresh lemon juice, cinnamon syrup, egg white',
    price: '5.500',
    allergies: '',
    allergies_long: '',
    allergiesList: [],
    category: 'TERES SIGNATURE COCKTAILS',
    src: '/cocktails/Whiskey Wick.png',
  },
  {
    alt: 'The Lantern cocktail',
    title: 'The Lantern',
    description: 'Tequila reposado, orange liqueur, fresh lime juice, mango purée, chili syrup, smoked salt',
    price: '5.500',
    allergies: '',
    allergies_long: '',
    allergiesList: [],
    category: 'TERES SIGNATURE COCKTAILS',
    src: '/cocktails/The Lantern.png',
  },
  // -------------------------- COCKTAILS --------------------------
  {
    alt: 'Mimosa cocktail',
    title: 'Mimosa',
    description: 'Champagne / Prosecco, fresh orange juice',
    price: '4.000',
    allergies: '',
    allergies_long: '',
    allergiesList: [],
    category: 'COCKTAILS',
    src: '/cocktails/Mimosa.png',
  },
  {
    alt: 'Bellini cocktail',
    title: 'Bellini',
    description: 'Prosecco, white peach purée',
    price: '4.000',
    allergies: '',
    allergies_long: '',
    allergiesList: [],
    category: 'COCKTAILS',
    src: '/cocktails/Bellini.png',
  },
  {
    alt: 'Sex on the Beach cocktail',
    title: 'Sex on the Beach',
    description: 'Vodka, peach schnapps, orange juice, cranberry juice',
    price: '4.000',
    allergies: '',
    allergies_long: '',
    allergiesList: [],
    category: 'COCKTAILS',
    src: '/cocktails/Sex on the Beach.png',
  },
  {
    alt: 'Espresso Martini cocktail',
    title: 'Espresso Martini',
    description: 'Vodka, coffee liqueur, fresh espresso, simple syrup',
    price: '4.000',
    allergies: '',
    allergies_long: '',
    allergiesList: [],
    category: 'COCKTAILS',
    src: '/cocktails/Espresso Martini.png',
  },
  {
    alt: 'Classic Daiquiri cocktail',
    title: 'Classic Daiquiri',
    description: 'White rum, fresh lime juice, simple syrup',
    price: '4.000',
    allergies: '',
    allergies_long: '',
    allergiesList: [],
    category: 'COCKTAILS',
    src: '/cocktails/Classic Daiquiri.png',
  },
  {
    alt: 'Flavoured Daiquiri cocktail',
    title: 'Flavoured Daiquiri',
    description: 'White rum, fresh lime juice, simple syrup, fruit purée',
    price: '4.000',
    allergies: '',
    allergies_long: '',
    allergiesList: [],
    category: 'COCKTAILS',
    src: '/cocktails/Flavoured Daiquiri.png',
  },
  {
    alt: 'Classic Mojito cocktail',
    title: 'Classic Mojito',
    description: 'White rum, fresh lime juice, mint leaves, sugar (or simple syrup), soda water',
    price: '4.000',
    allergies: '',
    allergies_long: '',
    allergiesList: [],
    category: 'COCKTAILS',
    src: '/cocktails/Classic Mojito.png',
  },
  {
    alt: 'Flavoured Mojito cocktail',
    title: 'Flavoured Mojito',
    description: 'White rum, fresh lime juice, mint leaves, simple syrup, soda water, fruit',
    price: '4.000',
    allergies: '',
    allergies_long: '',
    allergiesList: [],
    category: 'COCKTAILS',
    src: '/cocktails/Flavoured Mojito.png',
  },
  // -------------------------- CLASSIC COCKTAILS --------------------------
  {
    alt: 'Margarita Classic cocktail',
    title: 'Margarita Classic',
    description: 'Tequila, triple sec, fresh lime juice',
    price: '5.000', // Price from page-0006.jpg
    allergies: '',
    allergies_long: '',
    allergiesList: [],
    category: 'CLASSIC COCKTAILS',
    src: '/cocktails/Margarita Classic.png',
  },
  {
    alt: 'Piña Colada cocktail',
    title: 'Piña Colada',
    description: 'White rum, coconut cream, pineapple juice',
    price: '5.000', // Price from page-0006.jpg
    allergies: '',
    allergies_long: '',
    allergiesList: [],
    category: 'CLASSIC COCKTAILS',
    src: '/cocktails/Piña Colada.png',
  },
  {
    alt: 'Tequila Sunrise cocktail',
    title: 'Tequila Sunrise',
    description: 'Tequila, orange juice, grenadine',
    price: '5.000', // Price from page-0006.jpg
    allergies: '',
    allergies_long: '',
    allergiesList: [],
    category: 'CLASSIC COCKTAILS',
    src: '/cocktails/Tequila Sunrise.png',
  },
  {
    alt: 'Bloody Mary cocktail',
    title: 'Bloody Mary',
    description: 'Vodka, tomato juice, fresh lemon juice, Worcestershire sauce, hot sauce, salt, pepper',
    price: '5.200', // Price from page-0006.jpg
    allergies: '',
    allergies_long: '',
    allergiesList: [],
    category: 'CLASSIC COCKTAILS',
    src: '/cocktails/Bloody Mary.png',
  },
  {
    alt: 'Mojito Classic cocktail',
    title: 'Mojito Classic',
    description: 'White rum, fresh lime juice, mint leaves, sugar (or simple syrup), soda water',
    price: '5.000', // Price from page-0006.jpg
    allergies: '',
    allergies_long: '',
    allergiesList: [],
    category: 'CLASSIC COCKTAILS',
    src: '/cocktails/Classic Mojito.png', // Using the same image as "Classic Mojito" is appropriate
  },
  {
    alt: 'Zombie cocktail',
    title: 'Zombie',
    description: 'White rum, dark rum, overproof rum, apricot brandy, pineapple juice, lime juice, grenadine',
    price: '6.200', // Price from page-0006.jpg
    allergies: '',
    allergies_long: '',
    allergiesList: [],
    category: 'CLASSIC COCKTAILS',
    src: '/cocktails/Zombie.png',
  },
  {
    alt: 'Old Fashioned cocktail',
    title: 'Old Fashioned',
    description: 'Bourbon or rye whiskey, sugar, aromatic bitters',
    price: '5.300', // Price from page-0006.jpg
    allergies: '',
    allergies_long: '',
    allergiesList: [],
    category: 'CLASSIC COCKTAILS',
    src: '/cocktails/Old Fashioned.png',
  },
  {
    alt: 'Negroni cocktail',
    title: 'Negroni',
    description: 'Gin, Campari, sweet vermouth',
    price: '5.300', // Price from page-0006.jpg
    allergies: '',
    allergies_long: '',
    allergiesList: [],
    category: 'CLASSIC COCKTAILS',
    src: '/cocktails/Negroni.png',
  },
  {
    alt: 'Espresso Martini cocktail',
    title: 'Espresso Martini',
    description: 'Vodka, coffee liqueur, fresh espresso, simple syrup',
    price: '5.200', // Price from page-0006.jpg
    allergies: '',
    allergies_long: '',
    allergiesList: [],
    category: 'CLASSIC COCKTAILS',
    src: '/cocktails/Espresso Martini.png', // Using the same image as the "COCKTAILS" version
  },
  {
    alt: 'Amaretto Sour cocktail',
    title: 'Amaretto Sour',
    description: 'Amaretto, fresh lemon juice, simple syrup, egg white (optional)',
    price: '5.000', // Price from page-0006.jpg
    allergies: '',
    allergies_long: '',
    allergiesList: [],
    category: 'CLASSIC COCKTAILS',
    src: '/cocktails/Amaretto Sour.png',
  },
  {
    alt: 'Aperol Spritz cocktail',
    title: 'Aperol Spritz',
    description: 'Aperol, prosecco, soda water',
    price: '5.000', // Price from page-0006.jpg
    allergies: '',
    allergies_long: '',
    allergiesList: [],
    category: 'CLASSIC COCKTAILS',
    src: '/cocktails/Aperol Spritz.png',
  },
  {
    alt: 'Cosmopolitan cocktail',
    title: 'Cosmopolitan',
    description: 'Vodka, triple sec, cranberry juice, fresh lime juice',
    price: '5.000', // Price from page-0006.jpg
    allergies: '',
    allergies_long: '',
    allergiesList: [],
    category: 'CLASSIC COCKTAILS',
    src: '/cocktails/Cosmopolitan.png',
  },
  {
    alt: 'Passiontini cocktail',
    title: 'Passiontini',
    description: 'Vodka, passion fruit purée, vanilla syrup, fresh lime juice, prosecco (side)',
    price: '5.000', // Price from page-0006.jpg
    allergies: '',
    allergies_long: '',
    allergiesList: [],
    category: 'CLASSIC COCKTAILS',
    src: '/cocktails/Passiontini (Passion Fruit Martini).png',
  },
  {
    alt: 'Blue Hawaiian cocktail',
    title: 'Blue Hawaiian',
    description: 'White rum, blue curaçao, coconut cream, pineapple juice',
    price: '5.000', // Price from page-0006.jpg
    allergies: '',
    allergies_long: '',
    allergiesList: [],
    category: 'CLASSIC COCKTAILS',
    src: '/cocktails/Blue Hawaiian.png',
  },
  {
    alt: 'Whiskey Sour cocktail',
    title: 'Whiskey Sour',
    description: 'Bourbon whiskey, fresh lemon juice, simple syrup, egg white (optional)',
    price: '5.000', // Price from page-0006.jpg
    allergies: '',
    allergies_long: '',
    allergiesList: [],
    category: 'CLASSIC COCKTAILS',
    src: '/cocktails/Whiskey Sour.png',
  },
  {
    alt: 'Moscow Mule cocktail',
    title: 'Moscow Mule',
    description: 'Vodka, fresh lime juice, ginger beer',
    price: '6.200', // Price from page-0006.jpg
    allergies: '',
    allergies_long: '',
    allergiesList: [],
    category: 'CLASSIC COCKTAILS',
    src: '/cocktails/Moscow Mule.png',
  },
  {
    alt: 'Mai Tai cocktail',
    title: 'Mai Tai',
    description: 'White rum, dark rum, orange liqueur, orgeat syrup, lime juice',
    price: '6.200', // Price from page-0006.jpg
    allergies: '',
    allergies_long: '',
    allergiesList: [],
    category: 'CLASSIC COCKTAILS',
    src: '/cocktails/Mai Tai.png',
  },
  {
    alt: 'Gin Basil Smash cocktail',
    title: 'Gin Basil Smash',
    description: 'Gin, fresh lemon juice, simple syrup, fresh basil',
    price: '5.200', // Price from page-0006.jpg
    allergies: '',
    allergies_long: '',
    allergiesList: [],
    category: 'CLASSIC COCKTAILS',
    src: '/cocktails/Gin Basil Smash (Gin Basil).png',
  },
  {
    alt: 'Midori Sour cocktail',
    title: 'Midori Sour',
    description: 'Midori melon liqueur, vodka, fresh lemon or lime juice, simple syrup',
    price: '5.000', // Price from page-0006.jpg
    allergies: '',
    allergies_long: '',
    allergiesList: [],
    category: 'CLASSIC COCKTAILS',
    src: '/cocktails/Midori Sour.png',
  },
  {
    alt: 'Sangria cocktail',
    title: 'Sangria',
    description: 'Red wine, brandy, orange juice, fresh fruit, simple syrup',
    price: '5.000', // Price from page-0006.jpg
    allergies: '',
    allergies_long: '',
    allergiesList: [],
    category: 'CLASSIC COCKTAILS',
    src: '/cocktails/Sangria.png',
  },
  {
    alt: 'New York Sour cocktail',
    title: 'New York Sour',
    description: 'Bourbon whiskey, fresh lemon juice, simple syrup, red wine float',
    price: '5.000', // Price from page-0006.jpg
    allergies: '',
    allergies_long: '',
    allergiesList: [],
    category: 'CLASSIC COCKTAILS',
    src: '/cocktails/New York Sour.png',
  },
  {
    alt: 'Pisco Sour cocktail',
    title: 'Pisco Sour',
    description: 'Pisco, fresh lime juice, simple syrup, egg white, bitters',
    price: '5.000', // Price from page-0006.jpg
    allergies: '',
    allergies_long: '',
    allergiesList: [],
    category: 'CLASSIC COCKTAILS',
    src: '/cocktails/Pisco Sour.png',
  },
  {
    alt: 'Irish Coffee cocktail',
    title: 'Irish Coffee',
    description: 'Irish whiskey, hot coffee, sugar, cream',
    price: '4.800', // Price from page-0006.jpg
    allergies: '',
    allergies_long: '',
    allergiesList: [],
    category: 'CLASSIC COCKTAILS',
    src: '/cocktails/Irish Coffee.png',
  },
];
