export type CategoriesName =
  | 'SNACKS & APPETIZERS'
  | 'SALADS'
  | 'SUSHI'
  | 'CAVIAR & OYSTERS'
  | 'MAIN COURSES'
  | 'DESSERTS';

export type FoodItem = {
  alt: string;
  title: string;
  description: string;
  price: string;
  allergies: string;
  allergies_long: string;
  allergiesList: string[];
  category: CategoriesName;
  src: string;
};

export type FoodCategory = {
  id: CategoriesName;
  name: string;
  sortOrder: number;
};

export const foodCategories: Record<CategoriesName, FoodCategory> = {
  'SNACKS & APPETIZERS': {
    id: 'SNACKS & APPETIZERS',
    name: 'SNACKS & APPETIZERS',
    sortOrder: 0,
  },
  SALADS: {
    id: 'SALADS',
    name: 'SALADS',
    sortOrder: 1,
  },
  SUSHI: {
    id: 'SUSHI',
    name: 'SUSHI',
    sortOrder: 2,
  },
  'CAVIAR & OYSTERS': {
    id: 'CAVIAR & OYSTERS',
    name: 'CAVIAR & OYSTERS',
    sortOrder: 2,
  },
  'MAIN COURSES': {
    id: 'MAIN COURSES',
    name: 'MAIN COURSES',
    sortOrder: 3,
  },
  DESSERTS: {
    id: 'DESSERTS',
    name: 'DESSERTS',
    sortOrder: 4,
  },
};

export const foodData: FoodItem[] = [
  {
    src: '/img/menu/food_menu/edameme_sea_salt.jpg',
    alt: 'EDAMAME',
    title: 'Edamame',
    price: '4.000 BD',
    category: 'SNACKS & APPETIZERS',
    description: 'Sea Salt',
    allergies: 'V',
    allergies_long: 'Vegetarian',
    allergiesList: ['V'],
  },
  {
    src: '/img/menu/food_menu/edamame_sweet_miso.jpg',
    alt: 'EDAMAME',
    title: 'Edamame Miso',
    price: '4.500 BD',
    category: 'SNACKS & APPETIZERS',
    description: 'Sweet Miso Sauce, Sesame Seeds',
    allergies: 'SO, E, SS',
    allergies_long: 'Soy, Eggs, Sesame',
    allergiesList: ['SO', 'E', 'SS'],
  },
  {
    src: '/img/menu/food_menu/olives.jpg',
    alt: 'OLIVES',
    title: 'Cocktail Olives',
    price: '3.600 BD',
    category: 'SNACKS & APPETIZERS',
    description: 'Marinated Cocktail Olives',
    allergies: 'V',
    allergies_long: 'Vegetarian',
    allergiesList: ['V'],
  },
  {
    src: '/img/menu/food_menu/chicken_croquettes.jpg',
    alt: 'CHICKEN CROQUETTES',
    title: 'Chicken Croquettes',
    price: '4.500 BD',
    category: 'SNACKS & APPETIZERS',
    description: 'Chicken, Leek and Truffle Croquette, Garlic Mayonnaise and Parmesan Cheese',
    allergies: 'G, D, E',
    allergies_long: 'Gluten, Dairy, Eggs',
    allergiesList: ['G', 'D', 'E'],
  },
  {
    src: '/img/menu/food_menu/avocado_chips.jpg',
    alt: 'AVOCADO CHIPS',
    title: 'Avocado Chips',
    price: '4.800 BD',
    category: 'SNACKS & APPETIZERS',
    description: 'Crispy Avocado Fries, Yoghurt, Sriracha and Spring Onion Dipping Sauce',
    allergies: 'G, D, E, V',
    allergies_long: 'Gluten, Dairy, Eggs, Vegetarian',
    allergiesList: ['G', 'D', 'E', 'V'],
  },
  {
    src: '/img/menu/food_menu/volto_nuts.jpg',
    alt: 'VOLTO NUTS',
    title: 'Volto Nuts',
    price: '3.600 BD',
    category: 'SNACKS & APPETIZERS',
    description: 'Roasted and Spiced Cashew Nuts, Almond Nuts, and Peanuts',
    allergies: 'N, V',
    allergies_long: 'Nuts, Vegetarian',
    allergiesList: ['N', 'V'],
  },
  {
    src: '/img/menu/food_menu/prawn_pops.jpg',
    alt: 'PRAWN POPS',
    title: 'Prawn Pops',
    price: '4.800 BD',
    category: 'SNACKS & APPETIZERS',
    description: 'Crispy Prawns, Teriyaki Sauce, and Chives',
    allergies: 'G, D, S, SO',
    allergies_long: 'Gluten, Dairy, Fish and Shellfish, Soy',
    allergiesList: ['G', 'D', 'S', 'SO'],
  },
  {
    src: '/img/menu/food_menu/padron_peppers.jpg',
    alt: 'PADRON PEPPERS',
    title: 'Padron Peppers',
    price: '4.500 BD',
    category: 'SNACKS & APPETIZERS',
    description: 'Fried Spicy Peppers, Olive Oil, and Coarse Salt',
    allergies: 'V',
    allergies_long: 'Vegetarian',
    allergiesList: ['V'],
  },
  {
    src: '/img/menu/food_menu/cheese_board.jpeg',
    alt: 'CHEESE BOARD',
    title: 'Cheese Board',
    price: '8.000 BD',
    category: 'SNACKS & APPETIZERS',
    description: 'Hard and Semi-Hard Cheeses, Dried Fruits, Walnuts, Grapes, Olives, and Crackers',
    allergies: 'D, N, G, E',
    allergies_long: 'Dairy, Nuts, Gluten, Eggs',
    allergiesList: ['D', 'N', 'G', 'E'],
  },
  {
    src: '/img/menu/food_menu/tuna_tartare.jpg',
    alt: 'TUNA TARTARE',
    title: 'Yellow Fin Tuna Tartare',
    price: '9.000 BD',
    category: 'SNACKS & APPETIZERS',
    description: 'Yellow Fin Tuna, Tartare Sauce, and Seaweed Crisps',
    allergies: 'S, D, E, G',
    allergies_long: 'Fish and Shellfish, Dairy, Eggs, Gluten',
    allergiesList: ['S', 'D', 'E', 'G'],
  },
  {
    src: '/img/menu/food_menu/beef_kushiyaki.jpg',
    alt: 'BEEF KUSHIYAKI',
    title: 'Beef Kushiyaki',
    price: '8.000 BD',
    category: 'SNACKS & APPETIZERS',
    description: 'Grilled Marinated Wagyu Beef Skewers, Pickled Cucumber and Red Onion Salad, Sesame Seeds',
    allergies: 'SO, SS',
    allergies_long: 'Soy, Sesame',
    allergiesList: ['SO', 'SS'],
  },
  {
    src: '/img/menu/food_menu/volto_greek_salad.jpg',
    alt: 'VOLTO GREEK SALAD',
    title: "Volto 'Greek Salad'",
    price: '8.000 BD',
    category: 'SALADS',
    description: 'Beef Tomato, Red Peppers, Cucumber, Olives, Red Onion, Greek Feta Cheese, and Olive Oil',
    allergies: 'D, V',
    allergies_long: 'Dairy, Vegetarian',
    allergiesList: ['D', 'V'],
  },
  {
    src: '/img/menu/food_menu/burrata.jpg',
    alt: 'BURRATA',
    title: 'Burrata',
    price: '9.000 BD',
    category: 'SALADS',
    description:
      'Burrata Cheese, Blackberries, Teen, Hairloom and Cherry Tomato, Basil Pesto, and Balsamic Vinegar Glaze',
    allergies: 'D, V, N',
    allergies_long: 'Dairy, Vegetarian, Nuts',
    allergiesList: ['D', 'V', 'N'],
  },
  {
    src: '/img/menu/food_menu/green_volto.jpg',
    alt: 'GREEN VOLTO',
    title: 'Green Volto Salad',
    price: '6.500 BD',
    category: 'SALADS',
    description: 'Baby Gem, Asparagus, Broccolini, Edamame, Cucumber, Green Herbs and Labneh Dressing',
    allergies: 'D, V, SO',
    allergies_long: 'Dairy, Vegetarian, Soy',
    allergiesList: ['D', 'V', 'SO'],
  },
  {
    src: '/img/menu/food_menu/california.jpg',
    alt: 'CRAZY SUSHI CALIFORNIA',
    title: 'Crazy Sushi California',
    price: '7.500 BD',
    category: 'SUSHI',
    description: 'Crab Stick, Avocado, Cucumber, Tobiko, Spicy Mayonnaise',
    allergies: 'S. E, SO, SS',
    allergies_long: 'Fish and Shellfish, Eggs, Soy, Sesame',
    allergiesList: ['S', 'E', 'SO', 'SS'],
  },
  {
    src: '/img/menu/food_menu/jianto_seafood_balls.jpg',
    alt: 'JIANTO SEAFOOD BALLS',
    title: 'Jianto Seafood Balls',
    price: '8.000 BD',
    category: 'SUSHI',
    description: 'Salmon, Cripsy Shrimp, Avocado, Sriracha Mayonnaise',
    allergies: 'S, E, SO, SS',
    allergies_long: 'Fish and Shellfish, Eggs, Soy, Sesame',
    allergiesList: ['S', 'E', 'SO', 'SS'],
  },
  {
    src: '/img/menu/food_menu/summary_tuna_balls.jpg',
    alt: 'SUMMERY TUNA BALLS',
    title: 'Summery Tuna Balls',
    price: '8.000 BD',
    category: 'SUSHI',
    description: 'Tuna, Avocado, Cucumber, Ponzu Sauce',
    allergies: 'S, SO, E, SS',
    allergies_long: 'Fish and Shellfish, Soy, Eggs, Sesame',
    allergiesList: ['S', 'SO', 'E', 'SS'],
  },
  {
    src: '/img/menu/food_menu/fin_de_claire_oysters_half_a_dozen.jpg',
    alt: 'FIN DE CLAIRE OYSTERS HALF A DOZEN',
    title: 'Fin de Claire Oysters Half a Dozen',
    price: '16.000 BD',
    category: 'CAVIAR & OYSTERS',
    description:
      'Pomegranate, Shallots, Mint Oil \n Lemon, Chilli, and Bacon Butter\n Rockefeller-Spinach, Parmesan Cream, Crumbs',
    allergies: 'S,D,G',
    allergies_long: 'Fish and Shellfish, Dairy, Gluten',
    allergiesList: ['S', 'D', 'G'],
  },
  {
    src: '/img/menu/food_menu/fin_de_claire_oysters_dozen.jpg',
    alt: 'FIN DE CLAIRE OYSTERS DOZEN',
    title: 'Fin de Claire Oysters a Dozen',
    price: '28.000 BD',
    category: 'CAVIAR & OYSTERS',
    description:
      'Pomegranate, Shallots, Mint Oil \n Lemon, Chilli, and Bacon Butter\n Rockefeller-Spinach, Parmesan Cream, Crumbs',
    allergies: 'S,D,G',
    allergies_long: 'Fish and Shellfish, Dairy, Gluten',
    allergiesList: ['S', 'D', 'G'],
  },
  {
    src: '/img/menu/food_menu/oscietra_caviar.jpeg',
    alt: 'OSCIETRA CAVIAR',
    title: 'Oscietra Caviar - 50gr',
    price: '89.000 BD',
    category: 'CAVIAR & OYSTERS',
    description: 'Blinis, Shallots, Capers, Sour Cream, Chives, Boiled Egg',
    allergies: 'E, G, D',
    allergies_long: 'Eggs, Gluten, Dairy',
    allergiesList: ['E', 'G', 'D'],
  },
  {
    src: '/img/menu/food_menu/oscietra_caviar.jpeg',
    alt: 'OSCIETRA CAVIAR',
    title: 'Oscietra Caviar - 125gr',
    price: '175.000 BD',
    category: 'CAVIAR & OYSTERS',
    description: 'Blinis, Shallots, Capers, Sour Cream, Chives, Boiled Egg',
    allergies: 'E, G, D',
    allergies_long: 'Eggs, Gluten, Dairy',
    allergiesList: ['E', 'G', 'D'],
  },
  {
    src: '/img/menu/food_menu/beef_orzo.jpg',
    alt: 'BEEF ORZO',
    title: 'Beef Orzo',
    price: '19.000 BD',
    category: 'MAIN COURSES',
    description:
      'Pulled Slow-Cooked Beef Shortribs, Truffle, Carrot, Mushroom, Parsley, Seared Foie Gras, and Parmesan Cheese',
    allergies: 'G,D,E',
    allergies_long: 'Gluten, Dairy, Eggs',
    allergiesList: ['G', 'D', 'E'],
  },
  {
    src: '/img/menu/food_menu/seafood_orzo.jpg',
    alt: 'SEAFOOD ORZO',
    title: 'Seafood Orzo',
    price: '21.000 BD',
    category: 'MAIN COURSES',
    description: 'Prawns, Lobster Tail, Slow Roasted Tomato, Fennel, Feta Cheese, and Chives',
    allergies: 'S, G, D, E',
    allergies_long: 'Fish and Shellfish, Gluten, Dairy, Eggs',
    allergiesList: ['S', 'G', 'D', 'E'],
  },
  {
    src: '/img/menu/food_menu/lobster_tagliatelle.jpg',
    alt: 'LOBSTER TAGLIATELLE',
    title: 'Lobster Tagliatelle for 2 Guests to Share',
    price: '32.000 BD',
    category: 'MAIN COURSES',
    description: 'Whole Lobster, Seafood and Saffron Sauce, Roasted Red Peppers, Basil, Chilli and Lemon',
    allergies: 'S,G,D,E',
    allergies_long: 'Fish and Shellfish, Gluten, Dairy, Eggs',
    allergiesList: ['S', 'G', 'D', 'E'],
  },
  {
    src: '/img/menu/food_menu/volto_wagyu_sandwich.jpg',
    alt: 'VOLTO WAGYU SANDWICH',
    title: 'Volto Wagyu Sandwich - Volto Signature Dish',
    price: '18.000 BD',
    category: 'MAIN COURSES',
    description:
      "Breaded Wagyu Tenderloin Grade 4/5, 'Burger Patty', Volto 3.0 BBQ Sauce, Milk Bread, and Parmesan Fries",
    allergies: 'G, D, SO, E',
    allergies_long: 'Gluten, Dairy, Soy, Eggs',
    allergiesList: ['G', 'D', 'SO', 'E'],
  },
  {
    src: '/img/menu/food_menu/wagyu_striploin.jpg',
    alt: 'WAGYU STRIPLOIN',
    title: 'Wagyu Beef Striploin',
    price: '39.000 BD',
    category: 'MAIN COURSES',
    description: '250gr Wagyu Beef Striploin Grade 8/9, Chimichurri and Mushroom Sauce, Choice of 1 Side Dish',
    allergies: 'D',
    allergies_long: 'Dairy',
    allergiesList: ['D'],
  },
  {
    src: '/img/menu/food_menu/rib_eye.jpg',
    alt: 'RIB EYE',
    title: 'Wagyu Beef Rib Eye',
    price: '26.500 BD',
    category: 'MAIN COURSES',
    description: '300gr Wagyu Beef Rib Eye Grade 4/5, Chimichurri and Mushroom Sauce, Choice of 1 Side Dish',
    allergies: 'D',
    allergies_long: 'Dairy',
    allergiesList: ['D'],
  },
  {
    src: '/img/menu/food_menu/corn_fed_chicken.jpg',
    alt: 'CORN FED CHICKEN',
    title: 'Corn-Fed Chicken Breast',
    price: '10.000 BD',
    category: 'MAIN COURSES',
    description: 'Corn-Fed Chicken Breast, Chimichurri and Mushroom Sauce, Choice of 1 Side Dish',
    allergies: 'D',
    allergies_long: 'Dairy',
    allergiesList: ['D'],
  },
  {
    src: '/img/menu/food_menu/rock_lobster.jpg',
    alt: 'ROCK LOBSTER',
    title: 'Rock Lobster',
    price: '35.000 BD',
    category: 'MAIN COURSES',
    description: 'Omani Rock Lobster, Chimichurri and Lemon Dill Sauce, Choice of 1 Side Dish',
    allergies: 'D, S',
    allergies_long: 'Dairy, Fish and Shellfish',
    allergiesList: ['D', 'S'],
  },
  {
    src: '/img/menu/food_menu/prawns.jpg',
    alt: 'PRAWNS',
    title: 'Prawns U10',
    price: '16.500 BD',
    category: 'MAIN COURSES',
    description: '4 Prawns U10, Chimichurri and Lemon Dill Sauce, Choice of 1 Side Dish',
    allergies: 'D, S',
    allergies_long: 'Dairy, Fish and Shellfish',
    allergiesList: ['D', 'S'],
  },
  {
    src: '/img/menu/food_menu/salmon.jpg',
    alt: 'SALMON',
    title: 'Salmon Fillet',
    price: '13.500 BD',
    category: 'MAIN COURSES',
    description: 'Norwegian Salmon Fillet, Chimichurri and Lemon Dill Sauce, Choice of 1 Side Dish',
    allergies: 'D, S',
    allergies_long: 'Dairy, Fish and Shellfish',
    allergiesList: ['D', 'S'],
  },
  {
    src: '/img/menu/food_menu/seafood_platter.jpeg',
    alt: 'SEAFOOD PLATTER',
    title: 'Grilled Seafood Platter - for 2 Guests to Share - Volto Signature Dish',
    price: '52.000 BD',
    category: 'MAIN COURSES',
    description: 'Whole Lobster, U10 Prawns, Salmon Fillet, Chimichurri and Lemon Dill Sauce, Choice of 2 Side Dishes',
    allergies: 'D, S',
    allergies_long: 'Dairy, Fish and Shellfish',
    allergiesList: ['D', 'S'],
  },
  {
    src: '/img/menu/food_menu/ginger_sponge.jpg',
    alt: 'GINGER SPONGE',
    title: 'Sticky Ginger Sponge',
    price: '5.000 BD',
    category: 'DESSERTS',
    description: 'Ginger and Black Treacle Sponge, Fresh Mango, Toffee Sauce, and Vanilla Ice Cream',
    allergies: 'D, E, G',
    allergies_long: 'Dairy, Eggs, Gluten',
    allergiesList: ['D', 'E', 'G'],
  },
  {
    src: '/img/menu/food_menu/volto_chocolate_cake.jpeg',
    alt: 'VOLTO CHOCOLATE CAKE',
    title: 'Volto Chocolate Cake',
    price: '7.000 BD',
    category: 'DESSERTS',
    description: 'Dark Chocolate Cake, Mixed Berry Sauce, and Vanilla Cream',
    allergies: 'D, E, G,',
    allergies_long: 'Dairy, Eggs, Gluten,',
    allergiesList: ['D', 'E', 'G'],
  },
  {
    src: '/img/menu/food_menu/fruit_platter.jpeg',
    alt: 'FRUIT PLATTER',
    title: 'Fruit Platter',
    price: '6.000 BD',
    category: 'DESSERTS',
    description: 'Sliced Fresh Exotic Fruits',
    allergies: 'V',
    allergies_long: 'Vegetarian',
    allergiesList: ['V'],
  },
];
