services:
  reverse-proxy:
    build:
      context: ${PROJECT_ROOT}
      dockerfile: ./docker/build/Dockerfile.build.caddy
      args:
        VITE_NODE_ENV: ${NODE_ENV}
        VITE_API_URL: ${API_URL}

    ports:
      - ${PROXY_WEB_PORT}:3000
      - ${PROXY_ADMIN_PORT}:3001

    # command: 'sleep infinity'

  api:
    build:
      context: ${PROJECT_ROOT}
      dockerfile: docker/build/Dockerfile.build.api

    environment:
      NODE_ENV: ${NODE_ENV}
      API_PORT: ${API_PORT}
      ALLOWED_ORIGIN_PATTERNS: ${ALLOWED_ORIGIN_PATTERNS}
      FIREBASE_CERT: ${FIREBASE_CERT}

      IOS_MIN_SUPPORTED_VER: ${IOS_MIN_SUPPORTED_VER}
      ANDROID_MIN_SUPPORTED_VER: ${ANDROID_MIN_SUPPORTED_VER}

      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}

      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}

      MINIO_REGION: ${MINIO_REGION}
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_BUCKET: ${MINIO_BUCKET}
      MINIO_PORT: ${MINIO_PORT}

      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_SECURE: ${SMTP_SECURE}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}

    command: sh -c "pnpm start:api"

    depends_on:
      - db
      - redis
      - minio
      - mailpit

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER:?DB_USER is required}
      POSTGRES_PASSWORD: ${DB_PASSWORD:?DB_PASSWORD is required}
      POSTGRES_DB: ${DB_NAME:?DB_NAME is required}
      POSTGRES_PORT: ${DB_PORT}
    volumes:
      - db_build_volume:/var/lib/postgresql/data

  db-backup:
    build:
      context: ${PROJECT_ROOT}
      dockerfile: docker/build/Dockerfile.dbBackup.build

    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}
      DB_CONTAINER_NAME: db

    volumes:
      - ${PROJECT_ROOT}/backup:/backup
    depends_on:
      db:
        condition: service_started
    restart: unless-stopped

  redis:
    image: redis:latest
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-password}
    volumes:
      - redis_build_volume:/data
    command: ['redis-server', '--requirepass', '${REDIS_PASSWORD:-password}', '--appendonly', 'yes'] # enables persistence

  minio:
    image: quay.io/minio/minio:latest
    ports:
      - ${MINIO_PORT}:${MINIO_PORT}
      - '${MINIO_UI_PORT:?MINIO_UI_PORT is required}:9001' # Web UI
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_build_volume:/data
    command: server /data --console-address ":9001"

  minio-init:
    image: minio/mc
    depends_on:
      minio:
        condition: service_started

    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_PORT: ${MINIO_PORT}
      MINIO_BUCKET: ${MINIO_BUCKET}

    volumes:
      - ${PROJECT_ROOT}/scripts/init_minio.sh:/init_minio.sh:ro
      - ${PROJECT_ROOT}/seed/minio:/seed:ro

    entrypoint: ['/bin/sh', '/init_minio.sh']

  mailpit:
    image: axllent/mailpit
    restart: unless-stopped
    ports:
      - ${SMTP_UI_PORT:?SMTP_UI_PORT is required}:8025 # Web UI
    expose:
      - 1025

volumes:
  db_build_volume:
  redis_build_volume:
  minio_build_volume:
