import { prisma } from '@/bootstrap/db.init';
import { MediaStatus, ProductStatus } from '@/generated/prisma/enums';
import { fa, faker } from '@faker-js/faker';

faker.seed(1); // Ensure consistent fake data across runs

const prefix = 'products';

const fakeImages = [
  'airpods.jpg',
  'another_nike.jpg',
  'another_smartwatch.jpg',
  'aws_speaker.jpg',
  'blue_navy_backpack.jpg',
  'camera.jpg',
  'chanel.jpg',
  'colone.jpg',
  'cool_sneakers.jpg',
  'curology_shampoo.jpg',
  'high_heels.jpg',
  'hydro_flask.jpg',
  'iphone.jpg',
  'lipstick.jpg',
  'minimalist_watch.jpg',
  'mitzie_spray.jpg',
  'mountain_backpack.jpg',
  'nike.jpg',
  'ordinary_pack.jpg',
  'purple_shampoo.jpg',
  'rayban.jpg',
  'red_nike.jpg',
  'smart_watch.jpg',
  'sunglasses.jpg',
  'sunscreen.jpg',
  'vans.jpg',
  'watch.jpg',
];

export const fakeProducts = [
  {
    name: 'Apple AirPods Pro',
    description: 'Wireless noise-cancelling earbuds with premium sound quality',
    price: 249.99,
    status: faker.helpers.arrayElement(Object.values(ProductStatus)),
    createdAt: faker.date.past(),
    updatedAt: faker.date.recent(),
    thumbnail: {
      key: `${prefix}/airpods.jpg`,
      baseName: 'airpods.jpg',
      fileType: 'jpg',
      mimeType: 'image/jpeg',
      fileSize: 1024 * 500,
      status: MediaStatus.CONFIRMED,
      createdAt: faker.date.past(),
      updatedAt: faker.date.recent(),
    },
  },
  {
    name: 'Nike Air Max 270',
    description: 'Comfortable running shoes with Air Max technology',
    price: 150.0,
    status: faker.helpers.arrayElement(Object.values(ProductStatus)),
    createdAt: faker.date.past(),
    updatedAt: faker.date.recent(),
    thumbnail: {
      key: `${prefix}/another_nike.jpg`,
      baseName: 'another_nike.jpg',
      fileType: 'jpg',
      mimeType: 'image/jpeg',
      fileSize: 1024 * 500,
      status: MediaStatus.CONFIRMED,
      createdAt: faker.date.past(),
      updatedAt: faker.date.recent(),
    },
  },
  {
    name: 'Samsung Galaxy Watch',
    description: 'Advanced smartwatch with fitness tracking and GPS',
    price: 329.99,
    status: faker.helpers.arrayElement(Object.values(ProductStatus)),
    createdAt: faker.date.past(),
    updatedAt: faker.date.recent(),
    thumbnail: {
      key: `${prefix}/another_smartwatch.jpg`,
      baseName: 'another_smartwatch.jpg',
      fileType: 'jpg',
      mimeType: 'image/jpeg',
      fileSize: 1024 * 500,
      status: MediaStatus.CONFIRMED,
      createdAt: faker.date.past(),
      updatedAt: faker.date.recent(),
    },
  },
  {
    name: 'Amazon Echo Dot',
    description: 'Smart speaker with Alexa voice assistant',
    price: 49.99,
    status: faker.helpers.arrayElement(Object.values(ProductStatus)),
    createdAt: faker.date.past(),
    updatedAt: faker.date.recent(),
    thumbnail: {
      key: `${prefix}/aws_speaker.jpg`,
      baseName: 'aws_speaker.jpg',
      fileType: 'jpg',
      mimeType: 'image/jpeg',
      fileSize: 1024 * 500,
      status: MediaStatus.CONFIRMED,
      createdAt: faker.date.past(),
      updatedAt: faker.date.recent(),
    },
  },
  {
    name: 'Navy Blue Travel Backpack',
    description: 'Durable waterproof backpack perfect for travel',
    price: 89.99,
    status: faker.helpers.arrayElement(Object.values(ProductStatus)),
    createdAt: faker.date.past(),
    updatedAt: faker.date.recent(),
    thumbnail: {
      key: `${prefix}/blue_navy_backpack.jpg`,
      baseName: 'blue_navy_backpack.jpg',
      fileType: 'jpg',
      mimeType: 'image/jpeg',
      fileSize: 1024 * 500,
      status: MediaStatus.CONFIRMED,
      createdAt: faker.date.past(),
      updatedAt: faker.date.recent(),
    },
  },
  {
    name: 'Canon EOS DSLR Camera',
    description: 'Professional DSLR camera with high-resolution sensor',
    price: 899.99,
    status: faker.helpers.arrayElement(Object.values(ProductStatus)),
    createdAt: faker.date.past(),
    updatedAt: faker.date.recent(),
    thumbnail: {
      key: `${prefix}/camera.jpg`,
      baseName: 'camera.jpg',
      fileType: 'jpg',
      mimeType: 'image/jpeg',
      fileSize: 1024 * 500,
      status: MediaStatus.CONFIRMED,
      createdAt: faker.date.past(),
      updatedAt: faker.date.recent(),
    },
  },
  {
    name: 'Chanel No. 5 Perfume',
    description: 'Iconic luxury fragrance with timeless elegance',
    price: 135.0,
    status: faker.helpers.arrayElement(Object.values(ProductStatus)),
    createdAt: faker.date.past(),
    updatedAt: faker.date.recent(),
    thumbnail: {
      key: `${prefix}/chanel.jpg`,
      baseName: 'chanel.jpg',
      fileType: 'jpg',
      mimeType: 'image/jpeg',
      fileSize: 1024 * 500,
      status: MediaStatus.CONFIRMED,
      createdAt: faker.date.past(),
      updatedAt: faker.date.recent(),
    },
  },
  {
    name: 'Hugo Boss Cologne',
    description: 'Fresh masculine fragrance for everyday wear',
    price: 75.0,
    status: faker.helpers.arrayElement(Object.values(ProductStatus)),
    createdAt: faker.date.past(),
    updatedAt: faker.date.recent(),
    thumbnail: {
      key: `${prefix}/colone.jpg`,
      baseName: 'colone.jpg',
      fileType: 'jpg',
      mimeType: 'image/jpeg',
      fileSize: 1024 * 500,
      status: MediaStatus.CONFIRMED,
      createdAt: faker.date.past(),
      updatedAt: faker.date.recent(),
    },
  },
  {
    name: 'Adidas Ultraboost Sneakers',
    description: 'Premium running shoes with boost technology',
    price: 180.0,
    status: faker.helpers.arrayElement(Object.values(ProductStatus)),
    createdAt: faker.date.past(),
    updatedAt: faker.date.recent(),
    thumbnail: {
      key: `${prefix}/cool_sneakers.jpg`,
      baseName: 'cool_sneakers.jpg',
      fileType: 'jpg',
      mimeType: 'image/jpeg',
      fileSize: 1024 * 500,
      status: MediaStatus.CONFIRMED,
      createdAt: faker.date.past(),
      updatedAt: faker.date.recent(),
    },
  },
  {
    name: 'Curology Custom Shampoo',
    description: 'Personalized shampoo formula for your hair type',
    price: 28.0,
    status: faker.helpers.arrayElement(Object.values(ProductStatus)),
    createdAt: faker.date.past(),
    updatedAt: faker.date.recent(),
    thumbnail: {
      key: `${prefix}/curology_shampoo.jpg`,
      baseName: 'curology_shampoo.jpg',
      fileType: 'jpg',
      mimeType: 'image/jpeg',
      fileSize: 1024 * 500,
      status: MediaStatus.CONFIRMED,
      createdAt: faker.date.past(),
      updatedAt: faker.date.recent(),
    },
  },
  {
    name: 'Designer High Heels',
    description: 'Elegant designer high heels for special occasions',
    price: 295.0,
    status: faker.helpers.arrayElement(Object.values(ProductStatus)),
    createdAt: faker.date.past(),
    updatedAt: faker.date.recent(),
    thumbnail: {
      key: `${prefix}/high_heels.jpg`,
      baseName: 'high_heels.jpg',
      fileType: 'jpg',
      mimeType: 'image/jpeg',
      fileSize: 1024 * 500,
      status: MediaStatus.CONFIRMED,
      createdAt: faker.date.past(),
      updatedAt: faker.date.recent(),
    },
  },
  {
    name: 'Hydro Flask Water Bottle',
    description: 'Insulated stainless steel bottle keeps drinks cold 24 hours',
    price: 44.95,
    status: faker.helpers.arrayElement(Object.values(ProductStatus)),
    createdAt: faker.date.past(),
    updatedAt: faker.date.recent(),
    thumbnail: {
      key: `${prefix}/hydro_flask.jpg`,
      baseName: 'hydro_flask.jpg',
      fileType: 'jpg',
      mimeType: 'image/jpeg',
      fileSize: 1024 * 500,
      status: MediaStatus.CONFIRMED,
      createdAt: faker.date.past(),
      updatedAt: faker.date.recent(),
    },
  },
  {
    name: 'iPhone 15 Pro',
    description: 'Latest iPhone with titanium design and advanced camera',
    price: 999.0,
    status: faker.helpers.arrayElement(Object.values(ProductStatus)),
    createdAt: faker.date.past(),
    updatedAt: faker.date.recent(),
    thumbnail: {
      key: `${prefix}/iphone.jpg`,
      baseName: 'iphone.jpg',
      fileType: 'jpg',
      mimeType: 'image/jpeg',
      fileSize: 1024 * 500,
      status: MediaStatus.CONFIRMED,
      createdAt: faker.date.past(),
      updatedAt: faker.date.recent(),
    },
  },
  {
    name: 'MAC Ruby Woo Lipstick',
    description: 'Classic red matte lipstick with long-lasting formula',
    price: 19.0,
    status: faker.helpers.arrayElement(Object.values(ProductStatus)),
    createdAt: faker.date.past(),
    updatedAt: faker.date.recent(),
    thumbnail: {
      key: `${prefix}/lipstick.jpg`,
      baseName: 'lipstick.jpg',
      fileType: 'jpg',
      mimeType: 'image/jpeg',
      fileSize: 1024 * 500,
      status: MediaStatus.CONFIRMED,
      createdAt: faker.date.past(),
      updatedAt: faker.date.recent(),
    },
  },
  {
    name: 'Daniel Wellington Classic Watch',
    description: 'Minimalist design watch with genuine leather strap',
    price: 199.0,
    status: faker.helpers.arrayElement(Object.values(ProductStatus)),
    createdAt: faker.date.past(),
    updatedAt: faker.date.recent(),
    thumbnail: {
      key: `${prefix}/minimalist_watch.jpg`,
      baseName: 'minimalist_watch.jpg',
      fileType: 'jpg',
      mimeType: 'image/jpeg',
      fileSize: 1024 * 500,
      status: MediaStatus.CONFIRMED,
      createdAt: faker.date.past(),
      updatedAt: faker.date.recent(),
    },
  },
  {
    name: 'Mitzie Setting Spray',
    description: 'Long-lasting makeup setting spray for all-day wear',
    price: 24.0,
    status: faker.helpers.arrayElement(Object.values(ProductStatus)),
    createdAt: faker.date.past(),
    updatedAt: faker.date.recent(),
    thumbnail: {
      key: `${prefix}/mitzie_spray.jpg`,
      baseName: 'mitzie_spray.jpg',
      fileType: 'jpg',
      mimeType: 'image/jpeg',
      fileSize: 1024 * 500,
      status: MediaStatus.CONFIRMED,
      createdAt: faker.date.past(),
      updatedAt: faker.date.recent(),
    },
  },
  {
    name: 'Patagonia Hiking Backpack',
    description: 'Durable outdoor backpack for hiking adventures',
    price: 129.0,
    status: faker.helpers.arrayElement(Object.values(ProductStatus)),
    createdAt: faker.date.past(),
    updatedAt: faker.date.recent(),
    thumbnail: {
      key: `${prefix}/mountain_backpack.jpg`,
      baseName: 'mountain_backpack.jpg',
      fileType: 'jpg',
      mimeType: 'image/jpeg',
      fileSize: 1024 * 500,
      status: MediaStatus.CONFIRMED,
      createdAt: faker.date.past(),
      updatedAt: faker.date.recent(),
    },
  },
  {
    name: 'Nike Air Force 1',
    description: 'Classic white leather sneakers with timeless design',
    price: 110.0,
    status: faker.helpers.arrayElement(Object.values(ProductStatus)),
    createdAt: faker.date.past(),
    updatedAt: faker.date.recent(),
    thumbnail: {
      key: `${prefix}/nike.jpg`,
      baseName: 'nike.jpg',
      fileType: 'jpg',
      mimeType: 'image/jpeg',
      fileSize: 1024 * 500,
      status: MediaStatus.CONFIRMED,
      createdAt: faker.date.past(),
      updatedAt: faker.date.recent(),
    },
  },
  {
    name: 'The Ordinary Skincare Set',
    description: 'Complete skincare routine with premium ingredients',
    price: 35.0,
    status: faker.helpers.arrayElement(Object.values(ProductStatus)),
    createdAt: faker.date.past(),
    updatedAt: faker.date.recent(),
    thumbnail: {
      key: `${prefix}/ordinary_pack.jpg`,
      baseName: 'ordinary_pack.jpg',
      fileType: 'jpg',
      mimeType: 'image/jpeg',
      fileSize: 1024 * 500,
      status: MediaStatus.CONFIRMED,
      createdAt: faker.date.past(),
      updatedAt: faker.date.recent(),
    },
  },
  {
    name: 'Fanola Purple Shampoo',
    description: 'Purple shampoo for blonde and gray hair toning',
    price: 12.5,
    status: faker.helpers.arrayElement(Object.values(ProductStatus)),
    createdAt: faker.date.past(),
    updatedAt: faker.date.recent(),
    thumbnail: {
      key: `${prefix}/purple_shampoo.jpg`,
      baseName: 'purple_shampoo.jpg',
      fileType: 'jpg',
      mimeType: 'image/jpeg',
      fileSize: 1024 * 500,
      status: MediaStatus.CONFIRMED,
      createdAt: faker.date.past(),
      updatedAt: faker.date.recent(),
    },
  },
  {
    name: 'Ray-Ban Aviator Sunglasses',
    description: 'Classic aviator sunglasses with polarized lenses',
    price: 154.0,
    status: faker.helpers.arrayElement(Object.values(ProductStatus)),
    createdAt: faker.date.past(),
    updatedAt: faker.date.recent(),
    thumbnail: {
      key: `${prefix}/rayban.jpg`,
      baseName: 'rayban.jpg',
      fileType: 'jpg',
      mimeType: 'image/jpeg',
      fileSize: 1024 * 500,
      status: MediaStatus.CONFIRMED,
      createdAt: faker.date.past(),
      updatedAt: faker.date.recent(),
    },
  },
  {
    name: 'Nike Air Jordan 1 Red',
    description: 'Iconic basketball shoes in classic red colorway',
    price: 170.0,
    status: faker.helpers.arrayElement(Object.values(ProductStatus)),
    createdAt: faker.date.past(),
    updatedAt: faker.date.recent(),
    thumbnail: {
      key: `${prefix}/red_nike.jpg`,
      baseName: 'red_nike.jpg',
      fileType: 'jpg',
      mimeType: 'image/jpeg',
      fileSize: 1024 * 500,
      status: MediaStatus.CONFIRMED,
      createdAt: faker.date.past(),
      updatedAt: faker.date.recent(),
    },
  },
  {
    name: 'Apple Watch Series 9',
    description: 'Advanced fitness tracking with always-on display',
    price: 399.0,
    status: faker.helpers.arrayElement(Object.values(ProductStatus)),
    createdAt: faker.date.past(),
    updatedAt: faker.date.recent(),
    thumbnail: {
      key: `${prefix}/smart_watch.jpg`,
      baseName: 'smart_watch.jpg',
      fileType: 'jpg',
      mimeType: 'image/jpeg',
      fileSize: 1024 * 500,
      status: MediaStatus.CONFIRMED,
      createdAt: faker.date.past(),
      updatedAt: faker.date.recent(),
    },
  },
  {
    name: 'Oakley Sport Sunglasses',
    description: 'High-performance sunglasses with UV protection',
    price: 120.0,
    status: faker.helpers.arrayElement(Object.values(ProductStatus)),
    createdAt: faker.date.past(),
    updatedAt: faker.date.recent(),
    thumbnail: {
      key: `${prefix}/sunglasses.jpg`,
      baseName: 'sunglasses.jpg',
      fileType: 'jpg',
      mimeType: 'image/jpeg',
      fileSize: 1024 * 500,
      status: MediaStatus.CONFIRMED,
      createdAt: faker.date.past(),
      updatedAt: faker.date.recent(),
    },
  },
  {
    name: 'La Roche-Posay Sunscreen SPF 50',
    description: 'Broad-spectrum sunscreen for sensitive skin',
    price: 19.99,
    status: faker.helpers.arrayElement(Object.values(ProductStatus)),
    createdAt: faker.date.past(),
    updatedAt: faker.date.recent(),
    thumbnail: {
      key: `${prefix}/sunscreen.jpg`,
      baseName: 'sunscreen.jpg',
      fileType: 'jpg',
      mimeType: 'image/jpeg',
      fileSize: 1024 * 500,
      status: MediaStatus.CONFIRMED,
      createdAt: faker.date.past(),
      updatedAt: faker.date.recent(),
    },
  },
  {
    name: 'Vans Old Skool Sneakers',
    description: 'Classic skateboarding shoes with signature stripe',
    price: 65.0,
    status: faker.helpers.arrayElement(Object.values(ProductStatus)),
    createdAt: faker.date.past(),
    updatedAt: faker.date.recent(),
    thumbnail: {
      key: `${prefix}/vans.jpg`,
      baseName: 'vans.jpg',
      fileType: 'jpg',
      mimeType: 'image/jpeg',
      fileSize: 1024 * 500,
      status: MediaStatus.CONFIRMED,
      createdAt: faker.date.past(),
      updatedAt: faker.date.recent(),
    },
  },
  {
    name: 'Luxury Swiss Watch',
    description: 'Premium automatic watch with precision movement',
    price: 1250.0,
    status: faker.helpers.arrayElement(Object.values(ProductStatus)),
    createdAt: faker.date.past(),
    updatedAt: faker.date.recent(),
    thumbnail: {
      key: `${prefix}/watch.jpg`,
      baseName: 'watch.jpg',
      fileType: 'jpg',
      mimeType: 'image/jpeg',
      fileSize: 1024 * 500,
      status: MediaStatus.CONFIRMED,
      createdAt: faker.date.past(),
      updatedAt: faker.date.recent(),
    },
  },
];

export const seedProducts = async () => {
  for (const product of fakeProducts) {
    await prisma.product.upsert({
      where: { name: product.name },
      create: {
        description: product.description,
        name: product.name,
        price: product.price,
        status: product.status,
        thumbnail: {
          connectOrCreate: {
            where: { key: product.thumbnail.key },
            create: {
              key: product.thumbnail.key,
              baseName: product.thumbnail.baseName,
              fileType: product.thumbnail.fileType,
              mimeType: product.thumbnail.mimeType,
              fileSize: product.thumbnail.fileSize,
              status: product.thumbnail.status as MediaStatus,
            },
          },
        },
      },
      update: {},
    });
  }
};
